plugin:
    type: plugin
    name: Facebook
    description: |
        Facebook social plugin.
    fa_icon: facebook
    fields:
        facebook_account:
            type: text
            label: elcodi_plugin.facebook.facebook_account
